"""Add processed_at to Suggestion

Revision ID: 2872bf1b583d
Revises: 34fe471215c3
Create Date: 2025-08-15 01:12:01.323056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2872bf1b583d'
down_revision = '34fe471215c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggestion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('processed_by', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_suggestion_status'), ['status'], unique=False)
        batch_op.create_foreign_key(None, 'admin', ['processed_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggestion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_suggestion_status'))
        batch_op.drop_column('processed_by')
        batch_op.drop_column('processed_at')

    # ### end Alembic commands ###
