"""Initial tables

Revision ID: 34fe471215c3
Revises: 
Create Date: 2025-08-14 17:24:43.234802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34fe471215c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_department'))
        batch_op.drop_index(batch_op.f('idx_education_level'))
        batch_op.drop_index(batch_op.f('idx_end_date'))

    with op.batch_alter_table('saved_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('unique_user_job'))

    with op.batch_alter_table('suggestion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_status'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggestion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_status'), ['status'], unique=False)

    with op.batch_alter_table('saved_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_user_job'), ['user_id', 'job_id'], unique=True)

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_education_level'), ['education_level'], unique=False)
        batch_op.create_index(batch_op.f('idx_department'), ['department'], unique=False)

    # ### end Alembic commands ###
